### ISSUE TITLE
TypeError when enabling FAIL settings

### ISSUE THREAD

**Issue by jayvdb** [zlqm/openapi-toolset#2]
It might be a Django 3 thing, but here is a patch I needed to get the FAIL settings working

```diff
@@ -57,13 +59,12 @@ class APIDocCheckMiddleware:
 
     def raise_missing_doc(self, response, exc=None):
         if OPENAPI_CHECK_FAIL_ON_MISSING:
-            return HttpResponse('missing api doc', status_code=503)
+            return HttpResponse('missing api doc', status=503)
         return response
 
-
     def raise_mismatch(self, response, exc=None):
         if OPENAPI_CHECK_FAIL_FAST:
-            return HttpResponse('resp doesnot match doc', status_code=503)
+            return HttpResponse('resp doesnot match doc', status=503)
         return response
 
     def log(self, request, level, msg, *args, **kwargs):
```

**Comment by jayvdb** [comment]
However it is a bit odd to be using `HttpResponse` when it will likely being going to a client expecting a JSON response.  Raising a real exception will allow other parts of django to convert the exception into an appropriate response.  e.g. with DRF, I use drf-problems, which turns exceptions into 500 JSON responses.  And Django core will emit a HTML page possibly including debug if DEBUG is enabled.

**Comment by zlqm** [comment]
> However it is a bit odd to be using `HttpResponse` when it will likely being going to a client expecting a JSON response. Raising a real exception will allow other parts of django to convert the exception into an appropriate response. e.g. with DRF, I use drf-problems, which turns exceptions into 500 JSON responses. And Django core will emit a HTML page possibly including debug if DEBUG is enabled.

I have just fixed this problem. When api content mismatches schema, an Exception will be raised. You can see detailed message when `DEBUG` is enabled. But you cannot catch the exception and handle it with DRF because this project is based on Django middleware.

I think there are some difference between DRF and Django. 
1. DRF writes there own view and tries to catch exception raised inside view. see [EXCEPTION_HANDLER](https://github.com/encode/django-rest-framework/blob/master/rest_framework/views.py#L294)
2. Django also catches exception raised inside middlewares. see [django.core.handler.BaseHandler](https://github.com/django/django/blob/master/django/core/handlers/base.py#L37)

**Comment by jayvdb** [comment]
Thank you for detailed response.  I will re-test now.

**Comment by jayvdb** [comment]
Now I get
> 'APIDocCheckMiddleware' object has no attribute 'raise_missing_doc'

I've changed it to be `missing_doc_handler` and will keep testing.

**Comment by jayvdb** [comment]
> 'APIDocCheckMiddleware' object has no attribute 'raise_missing_doc'

This was fixed in [this commit](https://github.com/zlqm/openapi-toolset/pull/3/commits/fc85c4f546eddaab20ecd53816af35e6b7cc0c3d#diff-694f885203d93b45608359d2a3728f52L48)

> But you cannot catch the exception and handle it with DRF because this project is based on Django middleware.

Correct, it cant be handled in DRF.

However the request had `Accept: text/json` or similar, and DRF emitted a JSON response, and then this middleware breaks that, by knowingly emitting an exception which Django will convert into a HTML response that the client can not handle.

This may be OK for some users, but I think a better response would be a 501 error code with a custom message.  e.g. create a subclass of `APIException` for this, raise it, serialize it, and emit the json response.

Also sites will likely want to customise how these failures are handled, so creating settings for exception handler functions would be useful.  We would define a stable API for invoking these functions, and implement default handlers.  Similar to the DRF setting `EXCEPTION_HANDLER`, or even maybe re-using it.

**Comment by zlqm** [comment]
Good idea. I will add a exception hook at mismatching and allow user writing there own exception handler.

By default, it will generate a DEBUG page when DEBUG is enabled， otherwise return a 502 or 503 response. Response format will match the origin response content type. 

>  but I think a better response would be a 501 error code with a custom message.

501 means the request method is not supported by the server, which is not suitable fot this situation. May be 502(Bad Gateway) or 503(Service Unavailable) is better.

**Comment by jayvdb** [comment]
Note invalid requests should be a 4xx error.

> 501 means the request method is not supported by the server

Well, if the server response didnt match the advertised spec, then the requested method as defined by the OpenAPI spec is not supported by the server.

I dont like 502, which implies there is an intermediate server which has a temporary problem.  This is usually used by a nginx in front of Django, and could be very confusing.

503 is ok.

A custom 5xx is also ok, and IMO it would be useful to have a special 4xx & 5xx code so that the frontend knows what it means without ambiguity.

**Comment by zlqm** [comment]
custom mismatch handler is added. You can see a demo in this [commit](https://github.com/zlqm/openapi-toolset/commit/3b723d0d6980d72e4def68ed8555226708e7ccc6)
